### ISSUE TITLE
Setting pluginsDir key in constructor resets default plugin dir

### ISSUE THREAD

**Issue by void99** [mathmarques/Smarty-View#4]
When passing `pluginsDir` parameter to constructor, default Smarty plugins dir setting is being dropped, so Smarty could not find its default plugins (ie. `default` modifier). I think changing `setPluginsDir()` to `addPluginsDir()` in constructor will do the trick.

**Comment by mathmarques** [comment]
Thanks! Fixed on [1.1.1](https://github.com/mathmarques/Smarty-View/releases/tag/1.1.1)!
