### ISSUE TITLE
Registers a resource to fetch a template

### ISSUE THREAD

**Issue by elvispdosreis** [mathmarques/Smarty-View#5]
http://www.smarty.net/docs/en/api.register.resource.tpl

Please implement the resource method
So we can get template from custom methods and database

    /**
     * Unregister a resource
     *
     * @param string $type name of resource
     */
    public function unregisterResource($type)
    {
        $this->smarty->unregisterResource($type);
    }

    /**
     * Registers a resource to fetch a template
     *
     * @param string $type      name of resource
     * @param array  $functions array of functions to handle resource
     */
    public function registerResource($type, $functions)
    {
        $this->smarty->registerResource($type, $functions);
    }

**Comment by mathmarques** [comment]
For now you can do something like:
```php
$smarty = $view->getSmarty();
$smarty->unregisterResource($type);
```
