### ISSUE TITLE
baseUrl problem with Edge

### ISSUE THREAD

**Issue by drnasin** [mathmarques/Smarty-View#6]
Hello there, seems like

`$this->uri->getBaseUrl()`

Is using ->getAuthority() to build a scheme and host which results in http://username:password@localhost/<dir> and MS Edge is dying here...

Solution I used was to use $this->uri->getBasePath() instead of getBaseUrl() in SmartyPlugins->baseUrl function...

**Comment by mathmarques** [comment]
`getBaseUrl` and `getBasPath` have some problems... [See Here](https://github.com/slimphp/Slim/issues?utf8=%E2%9C%93&q=baseUrl)
So we provide an way to manual set your base path to be used by plugin.
Instead of:
```php
 $smartyPlugins = new \Slim\Views\SmartyPlugins($c['router'], $c['request']->getUri());
```
You can pass a string on the second argument:
```php
 $smartyPlugins = new \Slim\Views\SmartyPlugins($c['router'], 'your base path here');
```

**Comment by drnasin** [comment]
Ah I see, I was already wondering why is there a check if uri is string an then if it's object. Now I get it...thank you @mathmarques

**Comment by Rudloff** [comment]
Hello,
Here is a quick way to work around this issue:
```php
$smartyPlugins = new \Slim\Views\SmartyPlugins($c['router'], $c['request']->getUri()->withUserInfo(null));
```
