### ISSUE TITLE
Support Slim 4

### ISSUE THREAD

**Issue by elvispdosreis** [mathmarques/Smarty-View#8]
I posted a doubt on the slim forum, according to Message
Odan an active member of the forum, including a highly rated and highly voted forum and knows a lot about slim, would have no problem adding support for slim 4, could you please modify your composer.json

https://discourse.slimframework.com/t/slim-4-smarty-template/4567

**Comment by elvispdosreis** [comment]
Please verify  ***mathmarques/smarty-view "^2.0"*** not exist

**Comment by mgmbh** [comment]
@mathmarques thanks for your work on this!
dev-master works well with Slim 4 and Smarty 4, we have been using it for quite some time now. Do you mind tagging it as 2.0?

**Comment by mathmarques** [comment]
Just tagged 2.0 - https://github.com/mathmarques/Smarty-View/releases/tag/2.0.0
